<?php

namespace App\Doctrine\Type;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;

class MoneyType extends Type
{
    const MONEY = 'money';


    /**
     * Gets the SQL declaration snippet for a field of this type.
     *
     * @param array $fieldDeclaration The field declaration.
     * @param \Doctrine\DBAL\Platforms\AbstractPlatform $platform The currently used database platform.
     *
     * @return string
     */
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return 'money';
    }

    /**
     * Gets the name of this type.
     *
     * @return string
     *
     * @todo Needed?
     */
    public function getName()
    {
        return self::MONEY;
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        dd($value);
        return parent::convertToPHPValue($value, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToPHPValueSQL($sqlExpr, $platform)
    {
        dd($sqlExpr);
        return parent::convertToPHPValueSQL($sqlExpr, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        dd($value);
        return parent::convertToDatabaseValue($value, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToDatabaseValueSQL($sqlExpr, AbstractPlatform $platform)
    {
        dd($sqlExpr);
        return parent::convertToDatabaseValueSQL($sqlExpr, $platform); // TODO: Change the autogenerated stub
    }

    public function canRequireSQLConversion()
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function getMappedDatabaseTypes(AbstractPlatform $platform)
    {
//        dd('lol');
        return parent::getMappedDatabaseTypes($platform); // TODO: Change the autogenerated stub
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {


        return parent::requiresSQLCommentHint($platform); // TODO: Change the autogenerated stub
    }



}